version: '2'
services:
  collect:
    build: ./collect
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: dbuser
      PGPASSWORD: secret
      PGDATABASE: dbuser

  web:
    build: ./analyze
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: dbuser
      PGPASSWORD: secret
      PGDATABASE: dbuser
    ports:
      - "8000:8000"

  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
