version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: dbuser
      PGPASSWORD: secret
      PGDATABASE: dbuser
    ports:
      - "8000:8000"

  db:
    build: ./db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
